### ISSUE TITLE
Add social share buttons after pledge signup

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#100]
on the frontpage, remove the highfive image. in the space where the highfive image was, put in two buttons that ask people to share this page (one for fb and one for twitter).

![image](https://cloud.githubusercontent.com/assets/4324656/10023726/71454a54-6121-11e5-9176-1f4fd953d089.png)

**Comment by drewrwilson** [comment]
Looks like this: 
![image](https://cloud.githubusercontent.com/assets/4324656/10051795/6937d536-61f1-11e5-83cb-9a0e5a211c27.png)

How's this? Look good?

**Comment by dutch-embree** [comment]
Facebook share language: 
<meta name="og:title" content="I <3 the Internet + I Vote!">
      <meta name="og:url" content="http://internet2016.net">
      <meta name="og:description" content="I'm an #InternetVoter. I stand for free speech, access, privacy, choice and openness online. I want all candidates for office to support these principles and create meaningful policies to protect them. Join me and sign the pledge.">
      <meta name="og:image" content="https://s3.amazonaws.com/s3.freepress.net/images/action_internet2016_sticker.png">

title: "I <3 the Internet + I Vote!"
url: "http://internet2016.net"
description: "I'm an #InternetVoter. I stand for free speech, access, privacy, choice and openness online. I want all candidates for office to support these principles and create meaningful policies to protect them. Join me and sign the pledge."
image: https://s3.amazonaws.com/s3.freepress.net/images/action_internet2016_sticker.png

Twitter share language: 
I'm an #InternetVoter. I stand for free speech, access, privacy, choice & openness online. Learn more: internet2016.net @Internet_2016

**Comment by dutch-embree** [comment]
weird. the facebook markup isn't showing up for me

**Comment by drewrwilson** [comment]
@dutch-embree you can put the fb share stuff right into the [`_config.yml`](https://github.com/freepress/internet2016/blob/gh-pages/_config.yml) file. I put variables in there so you can update throughout the campaign, if you'd like. I'd recommend uploading the img to `assets` directory and linking to it with a link to like http://internet2016.net/assets/imgs/filename.png (instead of using an s3 link)

I just put in an update with the twitter share text

**Comment by dutch-embree** [comment]
awesome. thanks!

**Comment by dutch-embree** [comment]
this looks great - can you make these open in new tabs?

**Comment by drewrwilson** [comment]
sure
