### ISSUE TITLE
Horizontal menu on the policy platform is missing. Do you want it back?

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#102]
![image](https://cloud.githubusercontent.com/assets/4324656/10024118/b0d2307c-6123-11e5-8270-8c14605e26d6.png)

Did someone remove it on purpose or by accident? If accident, do you want it back?

**Comment by dutch-embree** [comment]
I liked that feature - I thought maybe it was decided to take it out when I wasn't looking. Not sure what happened to it.
