### ISSUE TITLE
Confirmation of submission, animation or redirect

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#22]
Can we do this post to actionkit asynchronously or does it have to be `POST`?

**Comment by drewrwilson** [comment]
right now it just redirects back to internet2016.net, which is fine. later I'll explore if we can do this post via ajax so we don't need to have a refresh on the page after signing the pledge

**Comment by dutch-embree** [comment]
it would be great if there was some indication that people's sign-up went through - even a little pop up? they will get a confirmation email but on the page itself would be nice.

**Comment by dutch-embree** [comment]
FWIW - this is not something that is included in Action Kit. I would like to make this a priority. can we do a modal like on FP.net?
![screen shot 2015-09-17 at 9 59 23 am](https://cloud.githubusercontent.com/assets/12643478/9935101/d387aebc-5d22-11e5-9e09-3cf8bb996a6e.png)

**Comment by drewrwilson** [comment]
Awesome, how's it done on fp.net? eg Is there any kind of actionkit config needed for this?

**Comment by dutch-embree** [comment]
I used chrome to "inspect element" and didn't see that it was connected to AK but I could be wrong ...

**Comment by drewrwilson** [comment]
Where is the thank you text from? Did you put it into action kit? Or in the drupal for freepress.net?

**Comment by dutch-embree** [comment]
yep, that's in drupal.

**Comment by drewrwilson** [comment]
when I go to freepress.net/actions the links seem to navigate me to an ActionKit hosted page. Could you share a link for this page that is on FP and does this popup? I need to see how they send data to AK and if I can do that from Internet2016 too

**Comment by drewrwilson** [comment]
Is that pic front the frontpage email sign up? 

![image](https://cloud.githubusercontent.com/assets/4324656/9937409/a5f2a63a-5d2e-11e5-9ded-6a5d6d470b3c.png)
