### ISSUE TITLE
Do we want a favicon designed?

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#31]
(Favicon is the little icon that appears in your browser next to the URL)

Right now the favicon is the freepress action fund logo: 

![image](https://cloud.githubusercontent.com/assets/4324656/9769555/ebe86a26-56f8-11e5-938d-b20634880f3c.png)

A digital heart favicon would be cool

**Comment by dutch-embree** [comment]
can it be the 8 bit heart?

**Comment by drewrwilson** [comment]
I would :heart: that. I don't know the requirements for favicons, it might be something we'd want the designer team to make

**Comment by dutch-embree** [comment]
I asked Rob to design something - he's going to send some options in the morning.

**Comment by dutch-embree** [comment]
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_16x16.png
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_16x16.svg
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_32x32.png
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_32x32.svg

**Comment by drewrwilson** [comment]
Cool! You can replace `favicon.ico` in the top level of this project to change it. I think (and I'm not 100% sure about this) that a `.ico` file can just be a `.png` renamed

**Comment by dutch-embree** [comment]
I don't know how to "replace favicon.ico in the top level of this project to change it" 

here are the .ico files 
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_16x16.ico
https://github.com/freepress/internet2016/blob/new-styles/assets/img/FP_Favicon_32x32.ico

**Comment by drewrwilson** [comment]
I did it. replaced the old favicon with the new one.
