### ISSUE TITLE
Re-order toolkits

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#33]
It's ordered by the dates in the filename. They can be reordered by changing the names of the files in in the [`_posts/toolkits/`](https://github.com/freepress/internet2016/tree/new-styles/_posts/toolkits) folder

**Comment by candacejeanne** [comment]
Order should be: 

Policy Platform
Take Action Online
Mobilize Your Community
Educate the Candidates
Teaming Up With Others
Resources

**Comment by dutch-embree** [comment]
I did this and I think I did it properly.

**Comment by drewrwilson** [comment]
yep!
