### ISSUE TITLE
Some of the markdown isn't generating headings & anchor links properly

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#35]
Some of the markdown content in the `_posts` folder isn't generating properly

![image](https://cloud.githubusercontent.com/assets/4324656/9769881/bd655f72-56fa-11e5-91f5-e4ca33c41634.png)

**Comment by candacejeanne** [comment]
Also there are some bulleted and numbered lists that aren't showing up right on the site but look fine in in GH.
