### ISSUE TITLE
Policy platform - icon for intro section?

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#39]
need to change the icon for the [intro section of the policy platform](https://github.com/freepress/internet2016/edit/new-styles/_posts/principles/2015-01-31-intro.md)

right now it's the same icon as the free speech section

**Comment by dutch-embree** [comment]
should we use the same icon that we use to represent the policy platform on the toolkit page: https://github.com/freepress/internet2016/blob/new-styles/assets/img/icons/toolkit-icons-Policy-Platform.png
