### ISSUE TITLE
Blog main page thumbnails

### ISSUE THREAD

**Issue by dutch-embree** [freepress/internet2016#41]
thumbnails are displaying huge - according to Rob's email with image specifics they should display: 249px X 249px

**Comment by drewrwilson** [comment]
Yep, the image size is fine, just needs some CSS to make it smaller on that blog list page. 

@dutch-embree, three options for ya:

One:
![image](https://cloud.githubusercontent.com/assets/4324656/9790865/64c3a458-57a6-11e5-9a85-8ce0a0d683ae.png)

Two: 
![image](https://cloud.githubusercontent.com/assets/4324656/9790909/994d51ec-57a6-11e5-9d00-e18116e9b4a0.png)

Three:
![image](https://cloud.githubusercontent.com/assets/4324656/9790900/8aa276f4-57a6-11e5-886f-a8c3992bcf9f.png)

which would you like?

**Comment by dutch-embree** [comment]
let's try the second option.
