### ISSUE TITLE
update facebook meta tags for internet2016.net

### ISSUE THREAD

**Issue by dutch-embree** [freepress/internet2016#42]
need to update with new language - right now it's pulling the party language see here: https://www.facebook.com/sharer/sharer.php?u=http%3A//internet2016.net/

**Comment by drewrwilson** [comment]
you can update it in [`_config.yml`](https://github.com/freepress/internet2016/blob/new-styles/_config.yml)

**Comment by dutch-embree** [comment]
great - I need to also update the image ... tips?

**Comment by drewrwilson** [comment]
Maybe a screenshot of the header bar from the front page? 

eg something like: 
![image](https://cloud.githubusercontent.com/assets/4324656/9772074/01ab652a-5708-11e5-8c16-255ff1aa11f5.png)

**Comment by dutch-embree** [comment]
I meant adding it - right now it's pulling from: "http://internet2016.net/img/internet2016-party-party-party.png" - can I just add a new image to assets and use that instead?

**Comment by drewrwilson** [comment]
Yep, add it to `assets/img`
