### ISSUE TITLE
Blog post images: Can we make it so the size is consistent?

### ISSUE THREAD

**Issue by dutch-embree** [freepress/internet2016#61]
Can we make it so the image posted sizes to fit within a predetermined size? Right now none of the sizing is consistent.

**Comment by drewrwilson** [comment]
Could you share a screenshot to show me what you mean?

(You can paste screen shots directly into comments here. On mac you can take it with cmd+shift+3 and to copy the screenshot to your clipboard, you can hold down ctrl while taking it. then you can paste it right  in a comment)
