### ISSUE TITLE
Facebook sharing language still old

### ISSUE THREAD

**Issue by candacejeanne** [freepress/internet2016#63]
No. 3 here: http://drewrwilson.com/internet2016/toolkits/take-action-online/#story

**Comment by drewrwilson** [comment]
Do you mean the content on that page? Or the preview on fb when a link to internet2016 is shared on fb?

**Comment by candacejeanne** [comment]
preview on fb

**Comment by drewrwilson** [comment]
Ok, that'll only change once this new code is on internet2016.net. Right now fb can only see the old internet2016.net so that's where fb is getting the preview info.

**Comment by drewrwilson** [comment]
![image](https://cloud.githubusercontent.com/assets/4324656/9818694/de1bfd38-5877-11e5-875e-b60093a2594c.png)

@candacejeanne Look good? If so, you can close this issue
