### ISSUE TITLE
Action Kit: sticker sign up isn't working

### ISSUE THREAD

**Issue by dutch-embree** [freepress/internet2016#72]
Pledge sign ups work - stickers signs up aren't being logged. I compared HTML and see the issue - not sure how to make the change so it doesn't break the drop down. 

This part of the html from Action Kit (that's not in the index) is where I'm focusing:

![image](https://cloud.githubusercontent.com/assets/12643478/9820362/72103c4e-5881-11e5-9050-5cbdaf606921.png)

Basically it needs to tell Action Kit to write to the userfield so that it gets saved in each users profile - which is how we'll be able to pull a list of people that signed up for the sticker.

**Comment by drewrwilson** [comment]
Ok, could you change the id of the sticker option in actionkit? The space is throwing it off. We don't need it to be "Yes, send me a sticker!" something like "sticker" is fine (lowercase prefered)

**Comment by drewrwilson** [comment]
Also, if you're making changes in there, could you change it to checkbox (instead of radiobutton)? if it's a single radio button someone can't uncheck it if they accidentally check it. May lead to more sticker requests than neccesary
