### ISSUE TITLE
Pledge sign up box: change color?

### ISSUE THREAD

**Issue by candacejeanne** [freepress/internet2016#74]
Can we make the pledge sign-up box pop more by changing the color to yellow?

**Comment by drewrwilson** [comment]
Do you mean the entire pledge box? If so, I don't think that'll look good, the section below it is yellow too so it'll just blend in. Plus, I'd have to restyle the button and text in there. 

![image](https://cloud.githubusercontent.com/assets/4324656/9826287/043aa97c-58a7-11e5-80b3-19cffdd8bf02.png)

**Comment by candacejeanne** [comment]
Sorry I mean the button that says "Sign the Pledge"

**Comment by dutch-embree** [comment]
that works for me - Drew can you make that change?

**Comment by drewrwilson** [comment]
Yep
