### ISSUE TITLE
Load time optimization

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#77]
- [x] Measure average page load times, eg using pingdom tools
- [x] Check filesizes of images and compress where possible
- [ ] Explore minifying css/js

Specifically, there are lots of big images on the policy platform page. Can that page load faster? Could we use some js library to lazy load images?

**Comment by drewrwilson** [comment]
via @tennysonholloway 

try to hit green on pagespeed insights so google doesn’t penalize your site: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Finternet2016.net%2F&tab=mobile

![image](https://cloud.githubusercontent.com/assets/4324656/9878547/47703d28-5b91-11e5-9ba1-12c69656867d.png)

**Comment by m4chinations** [comment]
Another good (free) test: 
Pingdom: http://tools.pingdom.com/fpt/#!/dbPhkE/internet2016.net

**Comment by drewrwilson** [comment]
todo: run all the images through https://tinypng.com/

**Comment by drewrwilson** [comment]
Running images through tinypng seems to be helping a lot. Will push up changes soon

![image](https://cloud.githubusercontent.com/assets/4324656/9915079/07089cc4-5c83-11e5-8f51-de2b747315a4.png)

**Comment by drewrwilson** [comment]
Policy Platform is definitely in need of some attention in this regard. 

![image](https://cloud.githubusercontent.com/assets/4324656/9916165/144bfc86-5c89-11e5-8be1-832b94317da5.png)

**Comment by drewrwilson** [comment]
img optimization for policy platform page:

![image](https://cloud.githubusercontent.com/assets/4324656/9916507/b9e9c0b4-5c8a-11e5-8b13-f1694bc3ea42.png)

could probably reduce the resolution too to get it even smaller

**Comment by drewrwilson** [comment]
d881ea17c1d0b854a35bf02d9c5322e490007e1a 

![image](https://cloud.githubusercontent.com/assets/4324656/9917194/4e7f0402-5c8e-11e5-88c0-dc6466587dc4.png)

**Comment by drewrwilson** [comment]
Seems like the largest load time chunk is loading images, which isn't surprising. maybe we could use lazy loader to load images via js to speed up load time 

http://www.appelsiini.net/projects/lazyload

**Comment by drewrwilson** [comment]
![image](https://cloud.githubusercontent.com/assets/4324656/9969672/ed1a6b3e-5e1d-11e5-8aab-a4bb4dcd7c85.png)

with lazy load

**Comment by drewrwilson** [comment]
after I do #93 and #98, I'm going to call this one done

**Comment by drewrwilson** [comment]
Closing this now. Will make a separate issue to explore minifying css/js
