### ISSUE TITLE
Mobile testing

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#78]
Test site with a few mobile devices and file any issues related to responsive display issues. 

Mainly thinking about the frontpage and the pledge

**Comment by dutch-embree** [comment]
I'm using browser stack to test, I've been testing all the pages on mobile and a few things have come up. I'll get into more detail on that later but for now here's a link to a bunch of screenshots of the front page on 23 different mobile devices: https://www.browserstack.com/screenshots/3bd587a8d9ee103858f1641d5899e08e1342519f

**Comment by dutch-embree** [comment]
Drew I invited you to join the FP browserstack team - once you're signed in/up for that, let me know.

**Comment by drewrwilson** [comment]
Cool, I signed up

**Comment by dutch-embree** [comment]
great - I took some screen shots on pages where things were looking funky: https://www.browserstack.com/accounts/issue-tracker - they are here

**Comment by drewrwilson** [comment]
Combining another issue from @candacejeanne:

"Sorry if this is covered elsewhere, but there's some weird stuff on the site when it loads on mobile (at least on an iPhone). Mostly just anywhere there is a box around text. I can see two issues:

1) "Sign the Pledge" button text cuts off at the boundary of the button

2) The boxes around "Read the Platform", "Check Out the Guide", and "Get the Toolkits" are smaller than the lines of text."
