### ISSUE TITLE
Is it possible to use HTTPS?

### ISSUE THREAD

**Issue by drewrwilson** [freepress/internet2016#79]
I think it's tricky with github pages, but if it's possible let's make HTTPS the default

**Comment by drewrwilson** [comment]
There's an open issue with github requesting this. Seems like there is a workable--but somewhat round-about--process that involves using cloudflare:

https://github.com/isaacs/github/issues/156

**Comment by tony7134** [comment]
Here is the link to the details for enabling full SSL (non-strict) on CloudFlare: https://github.com/isaacs/github/issues/156#issuecomment-110490178

**Comment by drewrwilson** [comment]
via @tennysonholloway:
"you can sign up for a free cloudflare account and get metrics + longer cache time + free https + set up a redirect http->https"

https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by m4chinations** [comment]
+1 i've had good experiences w/ cloudflare + github pages

**Comment by drewrwilson** [comment]
I'll be doing this soon. Likely within the next week. Going to wait to do it at an "off-time" for the site to minimize any possible downtime because of DNS propogation

**Comment by drewrwilson** [comment]
I tried this process on another project and it worked well. Should be quick to do, I'll do it late one evening this week to minimize any downtime

**Comment by drewrwilson** [comment]
@dutch-embree could you update the nameservers for internet2016.net to these? 

![image](https://cloud.githubusercontent.com/assets/4324656/10108600/e258a46e-638f-11e5-834c-b3bb2e696ea1.png)

for easy copying & pasting:
- `cortney.ns.cloudflare.com`
- `gabe.ns.cloudflare.com`

**Comment by dutch-embree** [comment]
I did this. I hope ...

**Comment by drewrwilson** [comment]
basic https working. changed most links to https. next need to set up a rule to force it

**Comment by drewrwilson** [comment]
redirecting http to https now. we don't have our own cert, but we have basic https set up for all pages now.

:lock: 

:balloon: :balloon: :balloon:
