### ISSUE TITLE
Possible to "handle" 404s more favorably?

### ISSUE THREAD

**Issue by tsammut** [freepress/internet2016#92]
Would it be possible to have more favorable handling of 404s on the site? Right now it appears to display a github default page.

**Comment by drewrwilson** [comment]
Thanks for pointing this out, @t1msammut! 

![image](https://cloud.githubusercontent.com/assets/4324656/10102872/f0e7a550-636e-11e5-90d6-1764aa3e1a55.png)

added a page that looks better than the github 404 page. Still could be improved upon, but closing this issue. if later we want to improve this 404 page, we could consult a designer and we'll start a new issue.
