### ISSUE TITLE
Mobile weirdness

### ISSUE THREAD

**Issue by candacejeanne** [freepress/internet2016#96]
Sorry if this is covered elsewhere, but there's some weird stuff on the site when it loads on mobile (at least on an iPhone). Mostly just anywhere there is a box around text. I can see two issues:

1) "Sign the Pledge" button text cuts off at the boundary of the button

2) The boxes around "Read the Platform", "Check Out the Guide", and "Get the Toolkits" are smaller than the lines of text. 

Let me know if you need screenshots or anything.

**Comment by dutch-embree** [comment]
I saw that too and took screen shots in browserstack - linked to here in this issue: https://github.com/freepress/internet2016/issues/78

**Comment by dutch-embree** [comment]
It's especially important to get mobile right - Action Kit said 60%+ of people are clicking through via mobile.
